const QUALITY_RULES = [
  {
    id: "SECRET.HARDCODED",
    severity: "critical",
    message: "Phát hiện credential có khả năng bị hardcode",
    remediation: "Chuyển credential sang biến môi trường hoặc secret manager",
    pattern: "(?:api[_-]?key|client[_-]?secret|password|jwt[_-]?secret|access[_-]?token)\\s*[:=]\\s*[\\\"'][^\\\"'${}]{8,}[\\\"']",
    flags: "i",
    redact: true,
  },
  {
    id: "SECRET.PRIVATE_KEY",
    severity: "critical",
    message: "Phát hiện private key trong source control",
    remediation: "Thu hồi key, xóa khỏi lịch sử Git và nạp từ secret manager",
    pattern: "-----BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----",
    flags: "i",
    redact: true,
  },
  {
    id: "CODE.TODO_COMMENT",
    severity: "medium",
    message: "TODO comment chưa được xử lý",
    remediation: "Hoàn thành công việc hoặc chuyển thành issue có liên kết",
    pattern: "^\\s*(?://|#|/\\*)\\s*TODO\\b",
    flags: "i",
  },
  {
    id: "ERROR.PRINT_STACKTRACE",
    severity: "high",
    message: "Không được in stack trace trực tiếp",
    remediation: "Dùng structured logger và error mapping tập trung",
    pattern: "(?:printStackTrace\\s*\\(|console\\.trace\\s*\\()",
  },
  {
    id: "ERROR.EMPTY_CATCH",
    severity: "high",
    message: "Empty catch làm mất lỗi",
    remediation: "Log có context và propagate/map lỗi phù hợp",
    pattern: "catch\\s*(?:\\([^)]*\\))?\\s*\\{\\s*\\}",
    flags: "g",
    scope: "file",
  },
  {
    id: "TRANSACTION.WRONG_LAYER",
    severity: "high",
    message: "Transaction boundary nằm ở Controller/Repository",
    remediation: "Đặt transaction boundary tại Service layer",
    pattern: "@Transactional\\b",
    pathPattern: "(?:controller|repository)",
    pathFlags: "i",
  },
  {
    id: "SQL.HARD_DELETE",
    severity: "critical",
    message: "Phát hiện hard delete trong SQL",
    remediation: "Dùng soft delete hoặc trạng thái nghiệp vụ",
    pattern: "\\bDELETE\\s+FROM\\b",
    flags: "i",
    extensions: [".sql"],
  },
  {
    id: "SQL.SELECT_ALL",
    severity: "medium",
    message: "SELECT * làm tăng rủi ro hiệu năng và rò rỉ dữ liệu",
    remediation: "Chỉ định rõ các cột cần đọc",
    pattern: "\\bSELECT\\s+\\*",
    flags: "i",
    extensions: [".sql"],
  },
];

module.exports = {
  QUALITY_RULES,
};
